"""add_stripe_columns

Revision ID: bcc109a22ca7
Revises: 
Create Date: 2026-04-28 03:32:46.843542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc109a22ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.create_unique_constraint('uq_order_payment', 'orders', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_payment', 'orders', type_='unique')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'stripe_session_id')
    # ### end Alembic commands ###
