"""add inventory logs and reorder threshold

Revision ID: ef360403feef
Revises: 5cb3acce045e
Create Date: 2026-05-21 03:54:24.744861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef360403feef'
down_revision: Union[str, Sequence[str], None] = '5cb3acce045e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # inventory_logs table already exists (created by Base.metadata.create_all)
    # Ensure indexes exist
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT indexname FROM pg_indexes WHERE tablename = 'inventory_logs'"
    ))
    existing_indexes = [row[0] for row in result.fetchall()]

    if 'ix_inventory_logs_change_type' not in existing_indexes:
        op.create_index(op.f('ix_inventory_logs_change_type'), 'inventory_logs', ['change_type'], unique=False)
    if 'ix_inventory_logs_created_at' not in existing_indexes:
        op.create_index(op.f('ix_inventory_logs_created_at'), 'inventory_logs', ['created_at'], unique=False)
    if 'ix_inventory_logs_product_id' not in existing_indexes:
        op.create_index(op.f('ix_inventory_logs_product_id'), 'inventory_logs', ['product_id'], unique=False)
    if 'ix_inventory_logs_reference_id' not in existing_indexes:
        op.create_index(op.f('ix_inventory_logs_reference_id'), 'inventory_logs', ['reference_id'], unique=False)

    op.drop_index(op.f('idx_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_product_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.drop_index(op.f('idx_orders_order_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_stripe_session_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('products', sa.Column('reorder_threshold', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop inventory_logs table (managed by Base.metadata.create_all)
    try:
        op.drop_index(op.f('ix_inventory_logs_reference_id'), table_name='inventory_logs')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_inventory_logs_product_id'), table_name='inventory_logs')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_inventory_logs_created_at'), table_name='inventory_logs')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_inventory_logs_change_type'), table_name='inventory_logs')
    except Exception:
        pass
    op.drop_column('products', 'reorder_threshold')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=False)
    op.create_index(op.f('idx_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('idx_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_index(op.f('idx_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('idx_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###
